name: Keep Streamlit App Awake

on:
  schedule:
    # Se ejecuta todos los días a las 12:00 UTC
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -s https://ordenador-manifest-v2.streamlit.app/ > /dev/null
